// js/gardenEngine.js — the Living Garden's growth state (internal name:
// Living Garden; the child-facing name of the shelf is My Garden).
//
// Product decision (the MY GARDEN sprint): every creation a child brings
// into the Studio grows the garden — an ENVIRONMENTAL feature of the
// workspace, never a game mechanic. This module owns exactly three
// things: the persisted growth record, the one event that grows it, and
// the state-driven decision of WHAT grows next. It draws nothing —
// js/gardenRenderer.js reads state() and does that — and it knows
// nothing about cameras, segmentation, OCR or asset extraction.
//
// THE EVENT IS THE WHOLE CONTRACT. Any creation source (the Bring It
// Alive scanner today; handwriting and future sources tomorrow) reports
// a successful capture either by dispatching
//   document.dispatchEvent(new CustomEvent('vihu:creation-captured',
//     { detail: { id: <capture id> } }))
// or by calling LivingGarden.captured({ id }). The garden never learns
// what the creation was — the sprint is explicit that creation TYPE
// must not determine growth ("The act of bringing something into the
// Garden causes growth"), so the detail carries no type field at all.
//
// ONE CAPTURE = ONE GROWTH. The capture id is remembered (a bounded
// recent-ids list) so a double dispatch — a retry, an over-eager
// caller, a re-render — cannot grow the garden twice for one creation.
// Re-rendering never calls captured() at all.
//
// WHAT IS PERSISTED IS DELIBERATELY TINY: { seed, events, recentIds }.
// The full element list is REGENERATED by replaying `events` growth
// steps from `seed` — each step consults the garden built so far (the
// active vine's tip, each zone's fullness), which is what the sprint
// means by "the result should depend on the current Garden state
// rather than simply the scan number". Replay makes persistence
// trivial, makes re-renders idempotent by construction, and keeps one
// child's garden the same shape every morning. The seed differs per
// garden, so two children's gardens are never the same shape.
//
// SCOPED TO THE MAGIC CARD like everything a child owns (Decision 19):
// the record is keyed by the active card id, falling back to a single
// traveller record when no card is claimed; claim() sweeps the
// traveller record to the new card exactly like CreatorLibrary's own
// claimUnowned. localStorage first — the record is a few dozen bytes —
// with the cloud follow-up disclosed in the sprint entry rather than
// invented here.
//
// NO COUNTS, NO LEVELS, NO PROGRESS. Nothing here is ever shown as a
// number. state() hands the renderer a list of things to draw; the
// event total exists only to replay growth and is exposed to nothing
// child-facing.
//
// GROWTH VOCABULARY (the sprint's): vines · sprigs (a short stem with
// paired leaves) · leaves · buds · occasional flowers, laid through six
// zones — origin, nearby growth, edge travel, branching, connections,
// blossoming. Coordinates are NORMALIZED to margin bands around the
// play area (the renderer maps them to real pixels around the real
// page, which is what keeps growth out of the play area whatever shape
// the page takes):
//   band 'left'   u: 0..1 across the left margin,  v: 0..1 top→bottom
//   band 'right'  u: 0..1 across the right margin, v: 0..1 top→bottom
//   band 'top'    u: 0..1 left→right,              v: 0..1 across the top margin
// The DENSITY CEILING is a hard element cap: past it, growth deepens —
// buds open into flowers, leaves fill — instead of spreading.
(function () {
  'use strict';

  const STORE_PREFIX = 'vihu-living-garden:';
  const TRAVELLER_KEY = STORE_PREFIX + 'traveller';
  const RECENT_IDS_MAX = 40;
  const DENSITY_CEILING = 110;   // elements; ~60 captures spread, then deepen

  let _listeners = [];
  let _cache = null;             // { key, record }

  function _cardId() {
    try {
      if (typeof MagicCard !== 'undefined' && MagicCard.activeId) return MagicCard.activeId() || null;
    } catch (e) {}
    try { return localStorage.getItem('vihu-magic-card-active-id') || null; } catch (e) { return null; }
  }
  function _storeKey() {
    const id = _cardId();
    return id ? (STORE_PREFIX + id) : TRAVELLER_KEY;
  }

  function _load() {
    const key = _storeKey();
    if (_cache && _cache.key === key) return _cache.record;
    let rec = null;
    try { rec = JSON.parse(localStorage.getItem(key) || 'null'); } catch (e) { rec = null; }
    if (!rec || typeof rec.events !== 'number' || typeof rec.seed !== 'number') {
      rec = { v: 1, seed: ((Date.now() ^ (Math.random() * 0x7fffffff)) >>> 0) % 0x7ffffffe + 1, events: 0, recentIds: [] };
    }
    if (!Array.isArray(rec.recentIds)) rec.recentIds = [];
    _cache = { key: key, record: rec };
    return rec;
  }
  function _save(rec) {
    try { localStorage.setItem(_storeKey(), JSON.stringify(rec)); } catch (e) {}
  }

  // A Traveller's garden becomes theirs when they claim a card — same
  // sweep CreatorLibrary.claimUnowned does, same one-way rule: only the
  // traveller record moves, never another Creator's.
  function claim() {
    const id = _cardId();
    if (!id) return;
    const target = STORE_PREFIX + id;
    try {
      if (localStorage.getItem(target)) return;           // the card already has a garden
      const orphan = localStorage.getItem(TRAVELLER_KEY);
      if (!orphan) return;
      localStorage.setItem(target, orphan);
      localStorage.removeItem(TRAVELLER_KEY);
      _cache = null;
    } catch (e) {}
  }

  // ---- deterministic replay ------------------------------------------------
  function _rng(seed) {
    let s = seed & 0x7fffffff;
    return function () { s = (s * 48271) % 0x7fffffff; return s / 0x7fffffff; };
  }

  // One growth step. `g` is the garden being built: it carries the
  // element list plus the growth frontier (which vine is alive, where
  // its tip is), and each step reads that state to decide what happens.
  function _step(g, rnd) {
    const el = g.elements;

    function vineNode(band, u, v) {
      el.push({ k: 'vine', band: band, u: u, v: v });
      g.tip = { band: band, u: u, v: v };
    }
    function jitter(x, amt) { return Math.max(0, Math.min(1, x + (rnd() - 0.5) * amt)); }

    // Past the ceiling the garden DEEPENS instead of spreading — the
    // element count NEVER rises again: buds open into flowers, then
    // existing leaves fill out a little, and that is all.
    if (el.length >= DENSITY_CEILING) {
      const budIx = el.findIndex(function (e) { return e.k === 'bud'; });
      if (budIx >= 0) { el[budIx] = { k: 'flower', band: el[budIx].band, u: el[budIx].u, v: el[budIx].v }; return; }
      if (rnd() < 0.3) {
        const fIx = el.findIndex(function (e) { return e.k === 'flower'; });
        if (fIx >= 0) { el[fIx] = { k: 'fruit', band: el[fIx].band, u: el[fIx].u, v: el[fIx].v }; return; }
      }
      const leaves = el.filter(function (e) { return e.k === 'leaf' && (e.s || 1) < 1.35; });
      if (leaves.length) { const L = leaves[Math.floor(rnd() * leaves.length)]; L.s = Math.min(1.35, (L.s || 1) + 0.12); }
      return;
    }

    const stage = g.stepCount;

    // Zone 1 — the origin: the very first capture plants one sprig at
    // the foot of the left margin. The garden's fixed point, forever.
    if (stage === 0) { el.push({ k: 'sprig', band: 'left', u: 0.55, v: 0.94, s: 1.1 }); g.tip = { band: 'left', u: 0.5, v: 0.9 }; return; }

    // Zone 2 — nearby growth: a young vine curls upward from the origin,
    // SLOWLY, leafing as it goes — at a dozen captures the garden should
    // read as a leafy young cluster, never a floor-to-ceiling wire (the
    // product owner, at 13 captures: the vine had already spanned the
    // column with bare stretches between tiny leaves).
    if (stage < 5) {
      // one leaf per node, sides alternating — pairs everywhere read as
      // clutter in a margin this size (the product owner's "nope")
      const side = (stage % 2 ? 1 : -1) * 0.18;
      vineNode('left', jitter(0.5, 0.18), g.tip.v - 0.045 - rnd() * 0.02);
      el.push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: g.tip.v, s: 0.8 + rnd() * 0.25 });
      return;
    }

    // Zone 3 — edge travel: the vine keeps climbing, still unhurried
    // (it reaches the upper half only around twenty captures), leaves
    // in pairs along the way, a sprig branching now and then.
    if (stage < 13) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      if (g.tip.band === 'left' && g.tip.v > 0.45) { vineNode('left', jitter(0.47, 0.18), g.tip.v - 0.055 - rnd() * 0.025); }
      else if (rnd() < 0.4) { el.push({ k: 'sprig', band: 'left', u: jitter(0.5, 0.3), v: g.tip.v + 0.15 + rnd() * 0.3, s: 0.8 + rnd() * 0.2 }); }
      el.push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: jitter(g.tip.v, 0.02), s: 0.8 + rnd() * 0.25 });
      return;
    }

    // Zone 4 — branching: the left vine finishes its climb; the right
    // side begins from its own foot; sprigs reach the mid-margins.
    if (stage < 24) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      if (g.tip.band === 'left' && g.tip.v > 0.14) {
        vineNode('left', jitter(0.47, 0.18), g.tip.v - 0.06 - rnd() * 0.03);
        el.push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: jitter(g.tip.v, 0.02), s: 0.8 + rnd() * 0.25 });
        return;
      }
      if (stage === 18 || (g.tip.band !== 'right' && rnd() < 0.4)) { vineNode('right', jitter(0.5, 0.18), 0.95); return; }
      if (g.tip.band === 'right' && g.tip.v > 0.5) { vineNode('right', jitter(0.5, 0.18), g.tip.v - 0.06 - rnd() * 0.03); el.push({ k: 'leaf', band: 'right', u: jitter(g.tip.u + side, 0.06), v: g.tip.v, s: 0.8 + rnd() * 0.25 }); return; }
      el.push({ k: 'sprig', band: rnd() < 0.5 ? 'left' : 'right', u: jitter(0.5, 0.25), v: 0.25 + rnd() * 0.5, s: 0.8 + rnd() * 0.2 });
      return;
    }

    // Anything that grows from here on grows ON a vine — a leaf or bud
    // in mid-air is decoration, and decoration was the "nope". The
    // anchor is a real vine node, chosen by the seeded rng.
    function onVine(kind, extra) {
      const vines = el.filter(function (e) { return e.k === 'vine'; });
      if (!vines.length) return false;
      const a = vines[Math.floor(rnd() * vines.length)];
      const side = (Math.floor(rnd() * 2) ? 1 : -1) * 0.16;
      el.push(Object.assign({ k: kind, band: a.band, u: jitter(a.u + side, 0.05), v: jitter(a.v, 0.02) }, extra || {}));
      return true;
    }

    // Zone 5 — connections: the right edge finishes its climb and the
    // top arc closes, so both sides read as ONE garden. First buds.
    if (stage < 40) {
      if (g.tip.band === 'right' && g.tip.v > 0.12) { vineNode('right', jitter(0.5, 0.18), g.tip.v - 0.09 - rnd() * 0.04); if (rnd() < 0.6) el.push({ k: 'leaf', band: 'right', u: jitter(g.tip.u + 0.16, 0.05), v: g.tip.v, s: 0.8 + rnd() * 0.2 }); return; }
      if (!g.topClosed) { g.topClosed = true; for (let u = 0.4; u <= 0.96; u += 0.14) el.push({ k: 'vine', band: 'top', u: u, v: jitter(0.5, 0.3) }); return; }
      if (rnd() < 0.35 && onVine('bud')) return;
      onVine('leaf', { s: 0.75 + rnd() * 0.25 });
      return;
    }

    // Zone 6 — blossoming, then FRUIT: flowers open where the vine is
    // OLDEST — near the origin first — and from the mid-fifties an
    // open flower now and then ripens into a small amber fruit ("when
    // will we get buds, flowers, fruits" — the product owner; the
    // vine's seasons are: buds from ~24 captures, flowers from ~40,
    // fruit from ~55, and past the ceiling everything keeps ripening).
    if (stage >= 55 && rnd() < 0.18) {
      const fIx = g.elements.findIndex(function (e) { return e.k === 'flower'; });
      if (fIx >= 0) { const f = g.elements[fIx]; g.elements[fIx] = { k: 'fruit', band: f.band, u: f.u, v: f.v }; return; }
    }
    if (rnd() < 0.3) {
      const budIx = g.elements.findIndex(function (e) { return e.k === 'bud'; });
      if (budIx >= 0) { const b = g.elements[budIx]; g.elements[budIx] = { k: 'flower', band: b.band, u: b.u, v: b.v }; return; }
      el.push({ k: 'flower', band: 'left', u: jitter(0.5, 0.2), v: 0.86 - (g.flowers = (g.flowers || 0) + 1) * 0.12 });
      return;
    }
    if (rnd() < 0.25 && onVine('bud')) return;
    onVine('leaf', { s: 0.75 + rnd() * 0.25 });
  }

  function _build(seed, events) {
    const rnd = _rng(seed);
    const g = { elements: [], tip: null, stepCount: 0, topClosed: false };
    for (let i = 0; i < events; i++) { _step(g, rnd); g.stepCount++; }
    return g.elements;
  }

  // ---- public surface ------------------------------------------------------
  function state() {
    const rec = _load();
    return { events: rec.events, elements: _build(rec.seed, rec.events) };
  }

  // grown(): how many elements the LAST capture added — the renderer
  // animates exactly that tail and nothing else.
  function captured(detail) {
    const id = detail && detail.id ? String(detail.id) : null;
    const rec = _load();
    if (id) {
      if (rec.recentIds.indexOf(id) >= 0) return { ok: true, grew: false };   // one capture = one growth
      rec.recentIds.push(id);
      if (rec.recentIds.length > RECENT_IDS_MAX) rec.recentIds.splice(0, rec.recentIds.length - RECENT_IDS_MAX);
    }
    const before = _build(rec.seed, rec.events).length;
    rec.events += 1;
    _save(rec);
    const after = _build(rec.seed, rec.events).length;
    const added = Math.max(0, after - before);
    _listeners.forEach(function (cb) { try { cb({ animate: true, added: added }); } catch (e) {} });
    return { ok: true, grew: true };
  }

  function onChange(cb) { if (typeof cb === 'function') _listeners.push(cb); }

  try {
    document.addEventListener('vihu:creation-captured', function (ev) {
      captured((ev && ev.detail) || {});
    });
  } catch (e) {}

  const api = { state: state, captured: captured, onChange: onChange, claim: claim };
  try { window.LivingGarden = api; } catch (e) {}
})();
