// js/gardenEngine.js — the Living Garden's growth state (internal name:
// Living Garden; the child-facing name of the shelf is My Garden).
//
// Product decision (the MY GARDEN sprint): every creation a child brings
// into the Studio grows the garden — an ENVIRONMENTAL feature of the
// workspace, never a game mechanic. This module owns exactly three
// things: the persisted growth record, the one event that grows it, and
// the state-driven decision of WHAT grows next. It draws nothing —
// js/gardenRenderer.js reads state() and does that — and it knows
// nothing about cameras, segmentation, OCR or asset extraction.
//
// THE EVENT IS THE WHOLE CONTRACT. Any creation source (the Bring It
// Alive scanner today; handwriting and future sources tomorrow) reports
// a successful capture either by dispatching
//   document.dispatchEvent(new CustomEvent('vihu:creation-captured',
//     { detail: { id: <capture id> } }))
// or by calling LivingGarden.captured({ id }). The garden never learns
// what the creation was — the sprint is explicit that creation TYPE
// must not determine growth ("The act of bringing something into the
// Garden causes growth"), so the detail carries no type field at all.
//
// ONE CAPTURE = ONE GROWTH. The capture id is remembered (a bounded
// recent-ids list) so a double dispatch — a retry, an over-eager
// caller, a re-render — cannot grow the garden twice for one creation.
// Re-rendering never calls captured() at all.
//
// WHAT IS PERSISTED IS DELIBERATELY TINY: { seed, events, recentIds }.
// The full element list is REGENERATED by replaying `events` growth
// steps from `seed` — each step consults the garden built so far (the
// active vine's tip, each zone's fullness), which is what the sprint
// means by "the result should depend on the current Garden state
// rather than simply the scan number". Replay makes persistence
// trivial, makes re-renders idempotent by construction, and keeps one
// child's garden the same shape every morning. The seed differs per
// garden, so two children's gardens are never the same shape.
//
// SCOPED TO THE MAGIC CARD like everything a child owns (Decision 19):
// the record is keyed by the active card id, falling back to a single
// traveller record when no card is claimed; claim() sweeps the
// traveller record to the new card exactly like CreatorLibrary's own
// claimUnowned. localStorage first — the record is a few dozen bytes —
// with the cloud follow-up disclosed in the sprint entry rather than
// invented here.
//
// NO COUNTS, NO LEVELS, NO PROGRESS. Nothing here is ever shown as a
// number. state() hands the renderer a list of things to draw; the
// event total exists only to replay growth and is exposed to nothing
// child-facing.
//
// GROWTH VOCABULARY (the sprint's): vines · sprigs (a short stem with
// paired leaves) · leaves · buds · occasional flowers · fruit, laid
// through six zones — origin, nearby growth, edge travel, branching,
// connections, blossoming. Each kind also has a small set of FORMS
// (a leaf is single, curled or paired; a sprig forks; a bud pairs; a
// flower opens wider or clusters; fruit hangs in twos), chosen by the
// same seeded rng. A form is a different expression of the same
// growth, NOT another object: a paired leaf is one leaf drawn as two
// blades, so the element count, the density ceiling and the replay are
// all exactly what they were.
//
// EVERY CAPTURE REPORTS WHAT CHANGED. A step returns
// { type, added:[ix], transformed:[ix], was:{ix:kind},
//   aged:[ix], fell:[ix], withered:[ix], removed:[element] } — because a
// growth event is not always an element appearing, and the renderer
// used to be told only how many had been added. Measured across five
// seeds over 120 captures each, 172 of 600 captures added nothing and
// therefore animated nothing; every capture past the ceiling was among
// them. The step now names the elements it touched, transformations
// included, and none of it is persisted — it is derived on replay like
// everything else. Coordinates are NORMALIZED to margin bands around the
// play area (the renderer maps them to real pixels around the real
// page, which is what keeps growth out of the play area whatever shape
// the page takes):
//   band 'left'   u: 0..1 across the left margin,  v: 0..1 top→bottom
//   band 'right'  u: 0..1 across the right margin, v: 0..1 top→bottom
//   band 'top'    u: 0..1 left→right,              v: 0..1 across the top margin
// DENSITY IS PRESSURE, NOT A CEILING. Past `density.ceiling` a growth
// step increasingly deepens — buds open into flowers, leaves fill —
// instead of spreading, and `density.hard` keeps the old cap as a
// safety valve rather than as the mechanism.
//
// AND THE GARDEN HAS A LIFE CYCLE. Grow → mature → age → wither → fall
// → gone, and the room that leaves behind is grown into by the ordinary
// growth step. Age is measured in CAPTURES, never in wall-clock time —
// a garden nobody visits does not decay while its maker is away. Every
// threshold is in ONE object, LIFECYCLE, so the pace can be tuned in
// one edit; the growth vocabulary and the six zones below are untouched
// by it, because aging runs BESIDE a growth step and never in place of
// one. A step therefore also reports { aged, fell, withered, removed },
// which is the same extension `transformed` already was: the renderer
// has to know which elements changed STATE, not only which appeared.
// None of it is persisted — `e.b` (the step an element was born at) is
// derived on replay like everything else, so the record is still
// exactly { seed, events, recentIds }.
(function () {
  'use strict';

  const STORE_PREFIX = 'vihu-living-garden:';
  const TRAVELLER_KEY = STORE_PREFIX + 'traveller';
  const RECENT_IDS_MAX = 40;

  // ---- THE LIFE CYCLE, and the ONE place its timing lives ------------------
  // Grow → mature → age → wither → fall → gone → and the room that
  // leaves behind is grown into by the ordinary growth step. Every
  // number the life cycle turns on is in this object and nowhere else,
  // because the sprint is explicit that this is an experiment and its
  // pace will be tuned: "Make the thresholds easy to tune from ONE
  // configuration object. Do not scatter timing constants."
  //
  // AGE IS MEASURED IN CAPTURES, NEVER IN WALL-CLOCK TIME. A child who
  // does not open the Studio for a week comes back to the garden they
  // left, not to one that decayed while they were away — the agency is
  // theirs. `elementAge = stepCount - e.b`, and `e.b` is stamped during
  // replay, so nothing new is persisted (see §17 in the sprint entry).
  //
  // GROWTH IS CAUSED BY CAPTURE; AGING IS CAUSED BY MATURITY. Aging is
  // therefore NOT a growth branch — it runs beside the growth step, not
  // instead of it, so it can never displace a structural move. That is
  // the same rule the seasons already obey ("structure outranks season")
  // taken to its conclusion: the life cycle never competes for the step
  // at all.
  const LIFECYCLE = {
    // Nothing ages at all until the garden itself is this old. A floor
    // rather than the active constraint — the youngest span below is far
    // longer — but it makes "a fresh garden never ages" true by
    // construction rather than by arithmetic.
    startAfter: 26,

    // Every element's own thresholds are shifted by up to half of this,
    // deterministically, from its own coordinate and birth step. Without
    // it a garden ages in COHORTS: the first vine's leaves are all born
    // within twenty captures of each other, so they all reach the same
    // threshold within a couple, and measured at seventy captures
    // nineteen of forty-two leaves turned at once. A season should
    // arrive, not be switched on. No rng is involved — the shift is a
    // function of values that are already stable across replay.
    spread: 16,

    // How many elements may change life stage in ONE capture. Density
    // pressure can make a great many elements due at once; without this
    // a garden crossing the ceiling would yellow all over in a single
    // step, which reads as a die-off rather than as a season. Oldest
    // first, one stage each, deterministically.
    maxPerCapture: 3,

    // DENSITY IS PRESSURE, NOT A WALL (the sprint's §11). Below `soft`
    // the garden ages at its own unhurried pace. Between `soft` and
    // `hard` the pressure ramps 0 → 1 and every span below shortens
    // toward `quicken` of itself. Past `ceiling` a growth step
    // increasingly DEEPENS (transforms what is there) instead of adding,
    // and `hard` is the old ceiling kept as a safety valve rather than
    // as the mechanism. The garden settles where the addition rate and
    // the departure rate meet — a living equilibrium, self-correcting in
    // both directions because relief is immediate: pressure falling
    // lengthens every remaining span again.
    density: { soft: 70, ceiling: 110, hard: 132 },
    quicken: 0.5,

    // The stages each kind passes through, as CUMULATIVE ages in
    // captures at zero pressure. Deliberately long: "the child should
    // first have enough time to become familiar with a growth element
    // before it starts disappearing", and "do NOT implement new leaf →
    // yellow → gone within a few captures".
    //
    // Every kind is different, which is the point of §7:
    //   leaf   fresh → pale gold → detaches, falls, rests on the floor → gone
    //   flower fades → petals fall and THE STEM REMAINS → gone
    //   fruit  never yellows; it ripens, drops, rests briefly → gone
    //   bud    a bud that never opened dries and drops, slowly
    //   sprig  young → established → dry → gone, and slowest of all,
    //          because "do not make large structural branches disappear
    //          too aggressively"
    //   vine   HAS NO LIFE CYCLE AND NEVER WILL. The vines are the
    //          garden's skeleton: every leaf, bud and flower is placed
    //          on one (onVine) and drawn attached to the nearest node,
    //          and the growth frontier itself is a point on the living
    //          tip. Aging the structure would not be a season, it would
    //          be demolition.
    stages: {
      leaf:   [{ p: 'age',    at: 52 }, { p: 'fall',   at: 82 },  { p: 'gone', at: 92 }],
      flower: [{ p: 'age',    at: 40 }, { p: 'wither', at: 66 },  { p: 'gone', at: 84 }],
      fruit:  [{ p: 'fall',   at: 30 }, { p: 'gone',   at: 40 }],
      bud:    [{ p: 'age',    at: 50 }, { p: 'fall',   at: 74 },  { p: 'gone', at: 84 }],
      sprig:  [{ p: 'wither', at: 88 }, { p: 'gone',   at: 118 }]
    }
  };

  let _listeners = [];
  let _cache = null;             // { key, record }

  function _cardId() {
    try {
      if (typeof MagicCard !== 'undefined' && MagicCard.activeId) return MagicCard.activeId() || null;
    } catch (e) {}
    try { return localStorage.getItem('vihu-magic-card-active-id') || null; } catch (e) { return null; }
  }
  function _storeKey() {
    const id = _cardId();
    return id ? (STORE_PREFIX + id) : TRAVELLER_KEY;
  }

  function _load() {
    const key = _storeKey();
    if (_cache && _cache.key === key) return _cache.record;
    let rec = null;
    try { rec = JSON.parse(localStorage.getItem(key) || 'null'); } catch (e) { rec = null; }
    if (!rec || typeof rec.events !== 'number' || typeof rec.seed !== 'number') {
      rec = { v: 1, seed: ((Date.now() ^ (Math.random() * 0x7fffffff)) >>> 0) % 0x7ffffffe + 1, events: 0, recentIds: [] };
    }
    if (!Array.isArray(rec.recentIds)) rec.recentIds = [];
    _cache = { key: key, record: rec };
    return rec;
  }
  function _save(rec) {
    try { localStorage.setItem(_storeKey(), JSON.stringify(rec)); } catch (e) {}
  }

  // A Traveller's garden becomes theirs when they claim a card — same
  // sweep CreatorLibrary.claimUnowned does, same one-way rule: only the
  // traveller record moves, never another Creator's.
  function claim() {
    const id = _cardId();
    if (!id) return;
    const target = STORE_PREFIX + id;
    try {
      if (localStorage.getItem(target)) return;           // the card already has a garden
      const orphan = localStorage.getItem(TRAVELLER_KEY);
      if (!orphan) return;
      localStorage.setItem(target, orphan);
      localStorage.removeItem(TRAVELLER_KEY);
      _cache = null;
    } catch (e) {}
  }

  // ---- deterministic replay ------------------------------------------------
  function _rng(seed) {
    let s = seed & 0x7fffffff;
    return function () { s = (s * 48271) % 0x7fffffff; return s / 0x7fffffff; };
  }

  // ---- the life cycle, replayed ------------------------------------------
  // An element is ALIVE (no phase) until it reaches the first stage its
  // kind has. After that it carries `p` (the phase name), `pi` (the
  // stage index it has reached, which only ever advances) and `pb` (the
  // step that phase began). All three are DERIVED during replay from
  // `e.b`, the step the element was born at — which is itself derived —
  // so the persisted record is still exactly { seed, events, recentIds }.
  // Nothing about the life cycle changes the persistence contract.
  function _pressure(n) {
    const d = LIFECYCLE.density;
    if (n <= d.soft) return 0;
    if (n >= d.hard) return 1;
    return (n - d.soft) / (d.hard - d.soft);
  }
  // The stage index a kind has earned at this age under this pressure.
  // -1 = whole. Pressure shortens every span toward `quicken` of itself.
  function _stageAt(e, age, press) {
    const st = LIFECYCLE.stages[e.k];
    if (!st) return -1;
    const q = 1 - (1 - LIFECYCLE.quicken) * press;
    const sp = LIFECYCLE.spread;
    const shift = sp ? ((((e.u * 7919) | 0) + (e.b || 0) * 131) % sp) - (sp >> 1) : 0;
    let out = -1;
    for (let i = 0; i < st.length; i++) if (age >= Math.round(st[i].at * q) + shift) out = i;
    return out;
  }
  function _alive(e) { return !e.p; }

  // One capture's worth of aging. It runs BESIDE the growth step and
  // never in place of it, it advances an element by at most ONE stage,
  // and it moves at most LIFECYCLE.maxPerCapture elements — so nothing
  // ever goes from green to gone in one capture and no capture is ever
  // a mass die-off. Oldest first, ties by index: no rng is involved in
  // WHO ages, only in where a falling thing lands.
  function _life(g, lrnd) {
    const el = g.elements;
    const res = { aged: [], fell: [], withered: [], removed: [] };
    if (g.stepCount < LIFECYCLE.startAfter) return res;
    const press = _pressure(el.length);
    const ready = [];
    for (let i = 0; i < el.length; i++) {
      const e = el[i];
      if (!LIFECYCLE.stages[e.k]) continue;
      const have = (typeof e.pi === 'number') ? e.pi : -1;
      const age = g.stepCount - (e.b || 0);
      if (_stageAt(e, age, press) > have) ready.push({ i: i, age: age, next: have + 1 });
    }
    if (!ready.length) return res;
    ready.sort(function (a, b) { return (b.age - a.age) || (a.i - b.i); });
    const gone = {};
    ready.slice(0, LIFECYCLE.maxPerCapture).forEach(function (r) {
      const e = el[r.i], st = LIFECYCLE.stages[e.k][r.next];
      e.pi = r.next; e.pb = g.stepCount;
      if (st.p === 'gone') { gone[r.i] = true; return; }
      e.p = st.p;
      if (st.p === 'fall') {
        // FALLING IS A REAL EVENT, not visible:false. The element keeps
        // existing — it detaches, drifts down and LIES ON THE GARDEN
        // FLOOR for a while before it goes. The engine decides both
        // ends of that journey so the renderer only ever draws a
        // transition that was already determined (§19).
        e.o = { u: e.u, v: e.v };
        e.v = 0.925 + lrnd() * 0.045;
        // AND IT DRIFTS TO THE SIDE ON THE WAY DOWN. A leaf that fell
        // straight was landing on the foot of its own vine — measured on
        // the right band, whose plant BEGINS at the floor, so five
        // fallen leaves were invisible inside the foliage they had just
        // left. Litter belongs beside the plant, not under it. Which
        // side is the side it was already leaning towards.
        e.u = 0.5 + (e.u < 0.5 ? -1 : 1) * (0.28 + lrnd() * 0.16);
        res.fell.push(r.i);
      } else if (st.p === 'wither') res.withered.push(r.i);
      else res.aged.push(r.i);
    });
    const goneIx = Object.keys(gone);
    if (!goneIx.length) return res;
    // Compact, and remap — everything this step reports must be an index
    // into the list the renderer is about to draw.
    const map = {};
    const kept = [];
    for (let i = 0; i < el.length; i++) {
      if (gone[i]) { res.removed.push(el[i]); continue; }
      map[i] = kept.length; kept.push(el[i]);
    }
    g.elements = kept;
    ['aged', 'fell', 'withered'].forEach(function (k) {
      res[k] = res[k].map(function (i) { return map[i]; }).filter(function (i) { return i !== undefined; });
    });
    return res;
  }

  // ---- what a growth step REPORTS -----------------------------------------
  // A growth event is not always an element appearing. A bud opening
  // into a flower, a flower ripening into fruit, a leaf filling out —
  // all of those change the garden without changing its SIZE, and the
  // renderer used to be told only `after.length - before.length`. That
  // one number was the whole cause of the silent captures: measured on
  // five seeds, 172 of 600 captures added nothing and therefore
  // animated nothing, every single capture past the density ceiling
  // among them.
  //
  // So a step now returns WHAT CHANGED — the indices of the elements it
  // added and the indices of the elements it transformed, plus the name
  // of the growth. Indices are the right identifier by construction: a
  // transformation replaces el[i] in place and a scale change mutates
  // it in place, so the index survives exactly the operations that used
  // to be invisible. Nothing about this is persisted; it is derived on
  // replay like everything else.
  const LEAF_FORMS = ['plain', 'curl', 'pair'];
  const FLOWER_FORMS = ['plain', 'open', 'cluster'];

  // One growth step. `g` is the garden being built: it carries the
  // element list plus the growth frontier (which vine is alive, where
  // its tip is), and each step reads that state to decide what happens.
  function _step(g, rnd) {
    const el = g.elements;
    const res = { type: null, added: [], transformed: [] };

    // Every element is stamped with the step it was born at — the whole
    // of the age model, and derived rather than persisted.
    function push(e) { e.b = g.stepCount; el.push(e); res.added.push(el.length - 1); return el.length - 1; }
    function vineNode(band, u, v) {
      push({ k: 'vine', band: band, u: u, v: v });
      g.tip = { band: band, u: u, v: v };
    }
    // A transformation remembers WHAT IT WAS. The renderer needs that
    // to show a bud actually opening rather than a flower appearing
    // where a bud used to be — and only a genuine kind change gets a
    // ghost, so promoting a fruit to a pair does not sprout a phantom
    // flower.
    // A TRANSFORMATION RESTARTS THE CLOCK. A flower that has just opened
    // is new AS A FLOWER, whatever the bud behind it had already lived
    // through — otherwise a long-waiting bud would open and fade in the
    // same handful of captures.
    function change(ix, e) {
      (res.was || (res.was = {}))[ix] = el[ix].k;
      e.b = g.stepCount;
      el[ix] = e; res.transformed.push(ix);
    }
    function touch(ix) { if (res.transformed.indexOf(ix) < 0) res.transformed.push(ix); }
    function jitter(x, amt) { return Math.max(0, Math.min(1, x + (rnd() - 0.5) * amt)); }
    // CONTROLLED VARIETY, not decoration. One seeded draw picks how a
    // leaf expresses itself — a single blade, a young curled one, or a
    // facing pair. The garden never gains an element for it: a pair is
    // ONE leaf drawn as two blades, so the density ceiling, the replay
    // and the element count are all untouched. "Do not make the Garden
    // grow more. Make the growth more interesting."
    function leafForm(curl, pair) {
      const r = rnd();
      if (r < curl) return 'curl';
      if (r < curl + pair) return 'pair';
      return 'plain';
    }
    // GROWTH ONLY EVER TOUCHES THE LIVING. A leaf on its way down does
    // not fill out; a faded flower does not ripen into fruit. Every
    // search below goes through these two, so there is no branch in
    // which a dying element could be promoted back into the season.
    function pickIx(fn) {
      const ixs = [];
      for (let i = 0; i < el.length; i++) if (_alive(el[i]) && fn(el[i])) ixs.push(i);
      return ixs.length ? ixs[Math.floor(rnd() * ixs.length)] : -1;
    }
    function firstIx(kind) {
      for (let i = 0; i < el.length; i++) if (_alive(el[i]) && el[i].k === kind) return i;
      return -1;
    }
    function someAlive(fn) { return el.some(function (e) { return _alive(e) && fn(e); }); }

    // Past the ceiling the garden DEEPENS instead of spreading — the
    // element count NEVER rises again. What it does instead is a pool
    // of STATE TRANSFORMATIONS, picked by the seeded rng: a bud opens,
    // a flower ripens, a leaf fills out, a flower opens wider, fruit
    // comes in pairs, a sprig forks. Scale is deliberately NOT in that
    // pool — it is the fallback for when nothing is left to transform,
    // because a garden whose only late behaviour is "the same leaves
    // get slightly bigger" has stopped answering the child.
    // THE CEILING IS PRESSURE NOW, NOT A WALL (§11). Under `ceiling` a
    // step adds as it always did. Between `ceiling` and `hard` a step
    // increasingly deepens instead — new growth replacing older growth
    // rather than piling on top of it — and `hard` keeps the old
    // behaviour as a safety valve. The short-circuit matters: at any
    // count at or below the ceiling the rng is not consulted at all, so
    // every garden younger than that is byte-identical to the one this
    // sprint inherited and the whole measured season pacing is untouched.
    const D = LIFECYCLE.density;
    const over = el.length > D.ceiling
      ? Math.min(1, (el.length - D.ceiling) / Math.max(1, D.hard - D.ceiling)) * 0.9 : 0;
    if (el.length >= D.hard || (over > 0 && rnd() < over)) {
      const budIx = firstIx('bud');
      const flIx = firstIx('flower');
      const pool = [];
      if (budIx >= 0) pool.push('open_bud');
      if (flIx >= 0) pool.push('ripen_flower');
      if (someAlive(function (e) { return e.k === 'leaf' && LEAF_FORMS.indexOf(e.f || 'plain') < LEAF_FORMS.length - 1; })) pool.push('fill_leaf');
      if (someAlive(function (e) { return e.k === 'flower' && FLOWER_FORMS.indexOf(e.f || 'plain') < FLOWER_FORMS.length - 1; })) pool.push('open_flower');
      if (someAlive(function (e) { return e.k === 'fruit' && (e.f || 'plain') === 'plain'; })) pool.push('pair_fruit');
      if (someAlive(function (e) { return e.k === 'sprig' && (e.f || 'plain') === 'plain'; })) pool.push('fork_sprig');
      const act = pool.length ? pool[Math.floor(rnd() * pool.length)] : 'grow_leaf';
      if (act === 'open_bud') {
        const b = el[budIx];
        change(budIx, { k: 'flower', band: b.band, u: b.u, v: b.v, f: rnd() < 0.3 ? 'open' : 'plain' });
        res.type = 'bud_opened';
      } else if (act === 'ripen_flower') {
        const f = el[flIx];
        change(flIx, { k: 'fruit', band: f.band, u: f.u, v: f.v, f: rnd() < 0.25 ? 'pair' : 'plain' });
        res.type = 'flower_ripened';
      } else if (act === 'fill_leaf') {
        const ix = pickIx(function (e) { return e.k === 'leaf' && LEAF_FORMS.indexOf(e.f || 'plain') < LEAF_FORMS.length - 1; });
        el[ix].f = LEAF_FORMS[LEAF_FORMS.indexOf(el[ix].f || 'plain') + 1];
        touch(ix); res.type = 'leaf_grew';
      } else if (act === 'open_flower') {
        const ix = pickIx(function (e) { return e.k === 'flower' && FLOWER_FORMS.indexOf(e.f || 'plain') < FLOWER_FORMS.length - 1; });
        el[ix].f = FLOWER_FORMS[FLOWER_FORMS.indexOf(el[ix].f || 'plain') + 1];
        touch(ix); res.type = 'flower_bloomed';
      } else if (act === 'pair_fruit') {
        const ix = pickIx(function (e) { return e.k === 'fruit' && (e.f || 'plain') === 'plain'; });
        el[ix].f = 'pair'; touch(ix); res.type = 'flower_ripened';
      } else if (act === 'fork_sprig') {
        const ix = pickIx(function (e) { return e.k === 'sprig' && (e.f || 'plain') === 'plain'; });
        el[ix].f = 'fork'; touch(ix); res.type = 'branch_created';
      } else {
        // The last resort, and it is still a real change: a leaf that
        // has room grows into it; a garden with nothing left to promote
        // rearranges one blade rather than doing nothing at all. There
        // is no path out of this branch that reports no change.
        let ix = pickIx(function (e) { return e.k === 'leaf' && (e.s || 1) < 1.35; });
        if (ix >= 0) { el[ix].s = Math.min(1.35, (el[ix].s || 1) + 0.12); touch(ix); res.type = 'leaf_grew'; }
        else {
          ix = pickIx(function (e) { return e.k === 'leaf'; });
          if (ix >= 0) { el[ix].f = LEAF_FORMS[(LEAF_FORMS.indexOf(el[ix].f || 'plain') + 1) % LEAF_FORMS.length]; touch(ix); res.type = 'leaf_grew'; }
          // A DENSE GARDEN THAT IS ALSO AN OLD ONE can reach this branch
          // with nothing living left to promote — every leaf on its way
          // down, every flower faded. Deepening has nothing to deepen,
          // so the garden GROWS: renewal is what a garden does when its
          // old growth has left, and there is no path out of this branch
          // that reports no change.
          else { onVine('leaf', { s: 0.75 + rnd() * 0.25, f: leafForm(0.22, 0.22) }); res.type = 'leaf_added'; }
        }
      }
      return res;
    }

    const stage = g.stepCount;

    // Zone 1 — the origin: the very first capture plants one sprig at
    // the foot of the left margin. The garden's fixed point, forever.
    if (stage === 0) {
      push({ k: 'sprig', band: 'left', u: 0.55, v: 0.94, s: 1.1 });
      g.tip = { band: 'left', u: 0.5, v: 0.9 };
      res.type = 'origin_created';
      return res;
    }

    // Zone 2 — nearby growth: a young vine curls upward from the origin,
    // SLOWLY, leafing as it goes — at a dozen captures the garden should
    // read as a leafy young cluster, never a floor-to-ceiling wire (the
    // product owner, at 13 captures: the vine had already spanned the
    // column with bare stretches between tiny leaves). Leaves are the
    // whole variation here: the first four captures are about ONE plant
    // establishing itself, so nothing forks and nothing branches yet.
    if (stage < 5) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      vineNode('left', jitter(0.5, 0.18), g.tip.v - 0.045 - rnd() * 0.02);
      push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: g.tip.v, s: 0.8 + rnd() * 0.25, f: leafForm(0.28, 0) });
      res.type = 'vine_extended';
      return res;
    }

    // Anything that grows from here on grows ON a vine — a leaf or bud
    // in mid-air is decoration, and decoration was the "nope". The
    // anchor is a real vine node, chosen by the seeded rng.
    function onVine(kind, extra) {
      const vines = el.filter(function (e) { return e.k === 'vine'; });
      if (!vines.length) return false;
      const a = vines[Math.floor(rnd() * vines.length)];
      const side = (Math.floor(rnd() * 2) ? 1 : -1) * 0.16;
      push(Object.assign({ k: kind, band: a.band, u: jitter(a.u + side, 0.05), v: jitter(a.v, 0.02) }, extra || {}));
      return true;
    }

    // THE SEASONS COME EARLY NOW, and the STRUCTURE does not move.
    // Measured on a real garden: buds waited for capture 24, flowers
    // for 40 and fruit for 55, so a garden anybody actually has — the
    // product owner's was about twenty — is a plain green vine and
    // stays one. Every colourful word in the vocabulary was gated
    // behind more scans than a child will make, which is why a whole
    // sprint of new growth "does not reflect on my existing growth".
    //
    // The pace is HALVED by opening the seasons sooner, never by
    // compressing the phases. Shortening the windows would starve the
    // vine's climb — each phase's step size is tuned to reach its own
    // height in its own number of steps, and the right vine is born
    // inside a branch that only runs once the left one is done — so
    // half the captures would have bought a shorter, coarser plant.
    // The plant is unchanged; it simply flowers younger.
    const BUD_FROM = 8, FLOWER_FROM = 18, FRUIT_FROM = 26;
    // A SEASON MUST NOT DEPEND ON THE DICE. Measured across the five
    // suite seeds, four gardens budded around capture 9-12 and one
    // waited until 30 — the roll simply kept missing. An average pace
    // is not a pace: that fifth child gets the plain green vine this
    // change exists to end. So once a season is well open and the
    // garden still has nothing of it, the next step TAKES it instead of
    // rolling again. Same growth step, same vocabulary, chosen rather
    // than won.
    function noneYet(kinds) {
      return !el.some(function (e) { return _alive(e) && kinds.indexOf(e.k) >= 0; });
    }
    const forceBud = stage >= BUD_FROM + 5 && noneYet(['bud', 'flower', 'fruit']);
    const forceFlower = stage >= FLOWER_FROM + 6 && noneYet(['flower', 'fruit']);

    // Zone 3 — edge travel: the vine keeps climbing, still unhurried
    // (it reaches the upper half only around twenty captures), leaves
    // in pairs along the way, a sprig branching now and then — and a
    // sprig can now fork, which is the first hint of the branching
    // phase to come.
    if (stage < 13) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      let type = 'leaf_added';
      // The first buds, well before the vine has finished travelling — a
      // young plant with a bud on it is still a young plant. Placed
      // AFTER the climb for the same reason as the phase below: the
      // vine getting where it is going is structure, a bud is season.
      if (g.tip.band === 'left' && g.tip.v > 0.45) { vineNode('left', jitter(0.47, 0.18), g.tip.v - 0.055 - rnd() * 0.025); type = 'vine_extended'; }
      else if (stage >= BUD_FROM && (forceBud || rnd() < 0.34) && onVine('bud', { f: rnd() < 0.18 ? 'pair' : 'plain' })) {
        res.type = 'bud_created';
        return res;
      }
      else if (rnd() < 0.4) { push({ k: 'sprig', band: 'left', u: jitter(0.5, 0.3), v: g.tip.v + 0.15 + rnd() * 0.3, s: 0.8 + rnd() * 0.2, f: rnd() < 0.3 ? 'fork' : 'plain' }); type = 'branch_created'; }
      push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: jitter(g.tip.v, 0.02), s: 0.8 + rnd() * 0.25, f: leafForm(0.2, 0.18) });
      res.type = type;
      return res;
    }

    // Zone 4 — branching: the left vine finishes its climb; the right
    // side begins from its own foot; sprigs reach the mid-margins.
    if (stage < 24) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      if (g.tip.band === 'left' && g.tip.v > 0.14) {
        vineNode('left', jitter(0.47, 0.18), g.tip.v - 0.06 - rnd() * 0.03);
        push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: jitter(g.tip.v, 0.02), s: 0.8 + rnd() * 0.25, f: leafForm(0.18, 0.22) });
        res.type = 'vine_extended';
        return res;
      }
      // A NEW CHAPTER, not another leaf (the sprint is explicit about
      // capture 18). The right side does not begin as a bare node — it
      // arrives with its own foot and its own first blade, so what the
      // child sees is a second plant starting rather than one more
      // increment of the first.
      if (!g.rightBorn && (stage === 18 || (g.tip.band !== 'right' && rnd() < 0.4))) {
        g.rightBorn = true;
        vineNode('right', jitter(0.5, 0.18), 0.95);
        push({ k: 'sprig', band: 'right', u: jitter(0.52, 0.12), v: 0.9, s: 0.9 + rnd() * 0.2, f: 'fork' });
        push({ k: 'leaf', band: 'right', u: jitter(0.55, 0.1), v: 0.92, s: 0.9 + rnd() * 0.2, f: leafForm(0, 0.4) });
        res.type = 'vine_born';
        return res;
      }
      if (g.tip.band === 'right' && g.tip.v > 0.5) {
        vineNode('right', jitter(0.5, 0.18), g.tip.v - 0.06 - rnd() * 0.03);
        push({ k: 'leaf', band: 'right', u: jitter(g.tip.u + side, 0.06), v: g.tip.v, s: 0.8 + rnd() * 0.25, f: leafForm(0.18, 0.22) });
        res.type = 'vine_extended';
        return res;
      }
      // THE SEASON FILLS WHAT THE STRUCTURE LEAVES, and never the other
      // way round. These sat at the top of this phase for one run and
      // seed 777 lost its right vine: a flower opening on capture 18
      // returned before the birth trigger could fire, and the sprint is
      // explicit that 18 is a new chapter. Structure first, colour in
      // the steps structure does not need.
      if (stage >= FLOWER_FROM && (forceFlower || rnd() < 0.5)) {
        const bIx = firstIx('bud');
        if (bIx >= 0) {
          const bb = el[bIx];
          change(bIx, { k: 'flower', band: bb.band, u: bb.u, v: bb.v, f: rnd() < 0.25 ? 'open' : 'plain' });
          res.type = 'flower_bloomed';
          return res;
        }
      }
      if (stage >= BUD_FROM && (forceBud || rnd() < 0.4) && onVine('bud', { f: rnd() < 0.2 ? 'pair' : 'plain' })) {
        res.type = 'bud_created';
        return res;
      }
      push({ k: 'sprig', band: rnd() < 0.5 ? 'left' : 'right', u: jitter(0.5, 0.25), v: 0.25 + rnd() * 0.5, s: 0.8 + rnd() * 0.2, f: rnd() < 0.45 ? 'fork' : 'plain' });
      res.type = 'branch_created';
      return res;
    }

    // Zone 5 — connections: the right edge finishes its climb and the
    // top arc closes, so both sides read as ONE garden. First buds.
    if (stage < 40) {
      // …and the first fruit ripens here rather than at 55, so a
      // garden of thirty captures has had a whole season rather than
      // only a green one.
      // MEASURED GAP: this phase grew buds and never opened one, so a
      // garden whose branching window happened not to roll a flower
      // waited all the way to 40 for its first colour — one seed in
      // five did exactly that. The season is continuous now.
      if (forceFlower || rnd() < 0.32) {
        const bIx2 = firstIx('bud');
        if (bIx2 >= 0) {
          const bb2 = el[bIx2];
          change(bIx2, { k: 'flower', band: bb2.band, u: bb2.u, v: bb2.v, f: rnd() < 0.25 ? 'open' : 'plain' });
          res.type = 'flower_bloomed';
          return res;
        }
      }
      if (stage >= FRUIT_FROM && rnd() < 0.16) {
        const fIx = firstIx('flower');
        if (fIx >= 0) {
          const ff = el[fIx];
          change(fIx, { k: 'fruit', band: ff.band, u: ff.u, v: ff.v, f: rnd() < 0.25 ? 'pair' : 'plain' });
          res.type = 'flower_ripened';
          return res;
        }
      }
      if (g.tip.band === 'right' && g.tip.v > 0.12) {
        vineNode('right', jitter(0.5, 0.18), g.tip.v - 0.09 - rnd() * 0.04);
        if (rnd() < 0.6) push({ k: 'leaf', band: 'right', u: jitter(g.tip.u + 0.16, 0.05), v: g.tip.v, s: 0.8 + rnd() * 0.2, f: leafForm(0.2, 0.2) });
        res.type = 'vine_extended';
        return res;
      }
      if (!g.topClosed) {
        g.topClosed = true;
        for (let u = 0.4; u <= 0.96; u += 0.14) push({ k: 'vine', band: 'top', u: u, v: jitter(0.5, 0.3) });
        res.type = 'connection_created';
        return res;
      }
      if (rnd() < 0.35 && onVine('bud', { f: rnd() < 0.22 ? 'pair' : 'plain' })) { res.type = 'bud_created'; return res; }
      onVine('leaf', { s: 0.75 + rnd() * 0.25, f: leafForm(0.22, 0.2) });
      res.type = 'leaf_added';
      return res;
    }

    // Zone 6 — blossoming, then FRUIT: flowers open where the vine is
    // OLDEST — near the origin first — and from the mid-fifties an
    // open flower now and then ripens into a small amber fruit ("when
    // will we get buds, flowers, fruits" — the product owner; the
    // vine's seasons are: buds from ~24 captures, flowers from ~40,
    // fruit from ~55, and past the ceiling everything keeps ripening).
    // This is the most varied phase by design: every form in the
    // vocabulary is reachable here.
    if (stage >= FRUIT_FROM && rnd() < 0.18) {
      const fIx = firstIx('flower');
      if (fIx >= 0) {
        const f = el[fIx];
        change(fIx, { k: 'fruit', band: f.band, u: f.u, v: f.v, f: rnd() < 0.25 ? 'pair' : 'plain' });
        res.type = 'flower_ripened';
        return res;
      }
    }
    if (rnd() < 0.3) {
      const budIx = firstIx('bud');
      if (budIx >= 0) {
        const b = el[budIx];
        change(budIx, { k: 'flower', band: b.band, u: b.u, v: b.v, f: rnd() < 0.3 ? 'open' : 'plain' });
        res.type = 'bud_opened';
        return res;
      }
      // BOUNDED, and it was not. This fallback stacks a flower a little
      // higher each time it fires, and nothing wrapped it: measured at
      // 340 captures it had walked to v = -3.5, three whole band heights
      // above the workspace, where _map puts it outside the layer and
      // the child never sees it. It is a pre-existing fault (16 off-band
      // elements across five seeds before this sprint) that the life
      // cycle made worse rather than caused — the old hard ceiling
      // stopped this branch running at all past ~90 captures, and a
      // garden that now stays under the ceiling forever keeps firing it
      // (36 off-band). Wrapping costs nothing, changes no other growth
      // decision — the same rng draws happen in the same order — and
      // gives the density budget back its lost elements.
      push({ k: 'flower', band: 'left', u: jitter(0.5, 0.2), v: 0.86 - ((g.flowers = (g.flowers || 0) + 1) % 6) * 0.12, f: rnd() < 0.25 ? 'open' : 'plain' });
      res.type = 'flower_bloomed';
      return res;
    }
    // A SPRIG CAN BE BORN HERE, and until now one could not be born at
    // all past capture 23 — every birth site is in a phase that ends
    // there. That was harmless while nothing died. With the life cycle
    // it is not: measured across five seeds, a garden holds 2-5 sprigs
    // at capture 100, none at 150, and none ever again. The forked
    // branches that gave it its structural variety leave and cannot be
    // replaced.
    //
    // Renewal (§13) has to be able to renew a KIND, not only a count —
    // a garden whose composition can only ever lose a vocabulary word
    // is not in equilibrium, it is in slow decline. Rare on purpose
    // (12%), and on a vine like everything else, so it is a branch off
    // the plant rather than a decoration dropped into a gap (§12).
    if (rnd() < 0.12 && onVine('sprig', { s: 0.8 + rnd() * 0.2, f: rnd() < 0.45 ? 'fork' : 'plain' })) {
      res.type = 'branch_created';
      return res;
    }
    if (rnd() < 0.25 && onVine('bud', { f: rnd() < 0.22 ? 'pair' : 'plain' })) { res.type = 'bud_created'; return res; }
    onVine('leaf', { s: 0.75 + rnd() * 0.25, f: leafForm(0.22, 0.22) });
    res.type = 'leaf_added';
    return res;
  }

  // THE LIFE CYCLE GETS ITS OWN SEEDED STREAM, and that is deliberate.
  // A second Park–Miller generator, seeded off the same garden seed, is
  // just as reproducible as one shared stream — and it keeps the life
  // cycle's draws OUT of the growth stream, so the season pacing this
  // sprint inherited (measured across thirteen seeds: bud 9/13/32,
  // flower 24/25/33, fruit 26/31/43) is not perturbed by a single leaf
  // deciding where to land. Same seed + same events → the same garden,
  // the same growth, the same aging and the same fallen leaves.
  function _lifeSeed(seed) { return ((seed ^ 0x5f3a7c1) >>> 0) % 0x7ffffffe + 1; }

  function _build(seed, events) {
    const rnd = _rng(seed);
    const lrnd = _rng(_lifeSeed(seed));
    const g = { elements: [], tip: null, stepCount: 0, topClosed: false, rightBorn: false };
    let last = null;
    for (let i = 0; i < events; i++) {
      // AGING FIRST, then growth — and never instead of it. Doing it in
      // this order means the compaction has already happened when the
      // growth step runs, so every index the step reports is an index
      // into the list the renderer is about to draw.
      const life = _life(g, lrnd);
      last = _step(g, rnd);
      last.aged = life.aged; last.fell = life.fell;
      last.withered = life.withered; last.removed = life.removed;
      g.stepCount++;
    }
    return { elements: g.elements, last: last };
  }

  // ---- public surface ------------------------------------------------------
  // state() is what a RE-RENDER reads, and it deliberately carries no
  // growth report: rendering must never look like growing (the sprint's
  // replay/render safety rule). The growth report travels on the change
  // event, which only captured() ever fires.
  function state() {
    const rec = _load();
    return { events: rec.events, elements: _build(rec.seed, rec.events).elements };
  }

  // ONE CAPTURE = ONE GROWTH STEP, and the variety happens INSIDE the
  // step — never by taking two. What the renderer is handed is the
  // step's own report: which elements appeared, which ones changed
  // without appearing, and what the growth was called.
  function captured(detail) {
    const id = detail && detail.id ? String(detail.id) : null;
    const rec = _load();
    if (id) {
      if (rec.recentIds.indexOf(id) >= 0) return { ok: true, grew: false };   // one capture = one growth
      rec.recentIds.push(id);
      if (rec.recentIds.length > RECENT_IDS_MAX) rec.recentIds.splice(0, rec.recentIds.length - RECENT_IDS_MAX);
    }
    rec.events += 1;
    _save(rec);
    const built = _build(rec.seed, rec.events);
    const growth = built.last
      || { type: null, added: [], transformed: [], aged: [], fell: [], withered: [], removed: [] };
    _listeners.forEach(function (cb) { try { cb({ animate: true, growth: growth }); } catch (e) {} });
    return { ok: true, grew: true, growth: growth };
  }

  function onChange(cb) { if (typeof cb === 'function') _listeners.push(cb); }

  try {
    document.addEventListener('vihu:creation-captured', function (ev) {
      captured((ev && ev.detail) || {});
    });
  } catch (e) {}

  // LIFECYCLE is exposed because the sprint asked for its pace to be
  // tunable from one place and because the suite has to be able to drive
  // a garden into density pressure that a healthy one never reaches. It
  // is the tuning surface, not product state: nothing in the Studio
  // reads it, nothing writes it, and it is not persisted.
  const api = { state: state, captured: captured, onChange: onChange, claim: claim,
                lifecycle: LIFECYCLE };
  try { window.LivingGarden = api; } catch (e) {}
})();
