// js/gardenEngine.js — the Living Garden's growth state (internal name:
// Living Garden; the child-facing name of the shelf is My Garden).
//
// Product decision (the MY GARDEN sprint): every creation a child brings
// into the Studio grows the garden — an ENVIRONMENTAL feature of the
// workspace, never a game mechanic. This module owns exactly three
// things: the persisted growth record, the one event that grows it, and
// the state-driven decision of WHAT grows next. It draws nothing —
// js/gardenRenderer.js reads state() and does that — and it knows
// nothing about cameras, segmentation, OCR or asset extraction.
//
// THE EVENT IS THE WHOLE CONTRACT. Any creation source (the Bring It
// Alive scanner today; handwriting and future sources tomorrow) reports
// a successful capture either by dispatching
//   document.dispatchEvent(new CustomEvent('vihu:creation-captured',
//     { detail: { id: <capture id> } }))
// or by calling LivingGarden.captured({ id }). The garden never learns
// what the creation was — the sprint is explicit that creation TYPE
// must not determine growth ("The act of bringing something into the
// Garden causes growth"), so the detail carries no type field at all.
//
// ONE CAPTURE = ONE GROWTH. The capture id is remembered (a bounded
// recent-ids list) so a double dispatch — a retry, an over-eager
// caller, a re-render — cannot grow the garden twice for one creation.
// Re-rendering never calls captured() at all.
//
// WHAT IS PERSISTED IS DELIBERATELY TINY: { seed, events, recentIds }.
// The full element list is REGENERATED by replaying `events` growth
// steps from `seed` — each step consults the garden built so far (the
// active vine's tip, each zone's fullness), which is what the sprint
// means by "the result should depend on the current Garden state
// rather than simply the scan number". Replay makes persistence
// trivial, makes re-renders idempotent by construction, and keeps one
// child's garden the same shape every morning. The seed differs per
// garden, so two children's gardens are never the same shape.
//
// SCOPED TO THE MAGIC CARD like everything a child owns (Decision 19):
// the record is keyed by the active card id, falling back to a single
// traveller record when no card is claimed; claim() sweeps the
// traveller record to the new card exactly like CreatorLibrary's own
// claimUnowned. localStorage first — the record is a few dozen bytes —
// with the cloud follow-up disclosed in the sprint entry rather than
// invented here.
//
// NO COUNTS, NO LEVELS, NO PROGRESS. Nothing here is ever shown as a
// number. state() hands the renderer a list of things to draw; the
// event total exists only to replay growth and is exposed to nothing
// child-facing.
//
// GROWTH VOCABULARY (the sprint's): vines · sprigs (a short stem with
// paired leaves) · leaves · buds · occasional flowers · fruit, laid
// through six zones — origin, nearby growth, edge travel, branching,
// connections, blossoming. Each kind also has a small set of FORMS
// (a leaf is single, curled or paired; a sprig forks; a bud pairs; a
// flower opens wider or clusters; fruit hangs in twos), chosen by the
// same seeded rng. A form is a different expression of the same
// growth, NOT another object: a paired leaf is one leaf drawn as two
// blades, so the element count, the density ceiling and the replay are
// all exactly what they were.
//
// EVERY CAPTURE REPORTS WHAT CHANGED. A step returns
// { type, added:[ix], transformed:[ix], was:{ix:kind} } — because a
// growth event is not always an element appearing, and the renderer
// used to be told only how many had been added. Measured across five
// seeds over 120 captures each, 172 of 600 captures added nothing and
// therefore animated nothing; every capture past the ceiling was among
// them. The step now names the elements it touched, transformations
// included, and none of it is persisted — it is derived on replay like
// everything else. Coordinates are NORMALIZED to margin bands around the
// play area (the renderer maps them to real pixels around the real
// page, which is what keeps growth out of the play area whatever shape
// the page takes):
//   band 'left'   u: 0..1 across the left margin,  v: 0..1 top→bottom
//   band 'right'  u: 0..1 across the right margin, v: 0..1 top→bottom
//   band 'top'    u: 0..1 left→right,              v: 0..1 across the top margin
// The DENSITY CEILING is a hard element cap: past it, growth deepens —
// buds open into flowers, leaves fill — instead of spreading.
(function () {
  'use strict';

  const STORE_PREFIX = 'vihu-living-garden:';
  const TRAVELLER_KEY = STORE_PREFIX + 'traveller';
  const RECENT_IDS_MAX = 40;
  const DENSITY_CEILING = 110;   // elements; ~60 captures spread, then deepen

  let _listeners = [];
  let _cache = null;             // { key, record }

  function _cardId() {
    try {
      if (typeof MagicCard !== 'undefined' && MagicCard.activeId) return MagicCard.activeId() || null;
    } catch (e) {}
    try { return localStorage.getItem('vihu-magic-card-active-id') || null; } catch (e) { return null; }
  }
  function _storeKey() {
    const id = _cardId();
    return id ? (STORE_PREFIX + id) : TRAVELLER_KEY;
  }

  function _load() {
    const key = _storeKey();
    if (_cache && _cache.key === key) return _cache.record;
    let rec = null;
    try { rec = JSON.parse(localStorage.getItem(key) || 'null'); } catch (e) { rec = null; }
    if (!rec || typeof rec.events !== 'number' || typeof rec.seed !== 'number') {
      rec = { v: 1, seed: ((Date.now() ^ (Math.random() * 0x7fffffff)) >>> 0) % 0x7ffffffe + 1, events: 0, recentIds: [] };
    }
    if (!Array.isArray(rec.recentIds)) rec.recentIds = [];
    _cache = { key: key, record: rec };
    return rec;
  }
  function _save(rec) {
    try { localStorage.setItem(_storeKey(), JSON.stringify(rec)); } catch (e) {}
  }

  // A Traveller's garden becomes theirs when they claim a card — same
  // sweep CreatorLibrary.claimUnowned does, same one-way rule: only the
  // traveller record moves, never another Creator's.
  function claim() {
    const id = _cardId();
    if (!id) return;
    const target = STORE_PREFIX + id;
    try {
      if (localStorage.getItem(target)) return;           // the card already has a garden
      const orphan = localStorage.getItem(TRAVELLER_KEY);
      if (!orphan) return;
      localStorage.setItem(target, orphan);
      localStorage.removeItem(TRAVELLER_KEY);
      _cache = null;
    } catch (e) {}
  }

  // ---- deterministic replay ------------------------------------------------
  function _rng(seed) {
    let s = seed & 0x7fffffff;
    return function () { s = (s * 48271) % 0x7fffffff; return s / 0x7fffffff; };
  }

  // ---- what a growth step REPORTS -----------------------------------------
  // A growth event is not always an element appearing. A bud opening
  // into a flower, a flower ripening into fruit, a leaf filling out —
  // all of those change the garden without changing its SIZE, and the
  // renderer used to be told only `after.length - before.length`. That
  // one number was the whole cause of the silent captures: measured on
  // five seeds, 172 of 600 captures added nothing and therefore
  // animated nothing, every single capture past the density ceiling
  // among them.
  //
  // So a step now returns WHAT CHANGED — the indices of the elements it
  // added and the indices of the elements it transformed, plus the name
  // of the growth. Indices are the right identifier by construction: a
  // transformation replaces el[i] in place and a scale change mutates
  // it in place, so the index survives exactly the operations that used
  // to be invisible. Nothing about this is persisted; it is derived on
  // replay like everything else.
  const LEAF_FORMS = ['plain', 'curl', 'pair'];
  const FLOWER_FORMS = ['plain', 'open', 'cluster'];

  // One growth step. `g` is the garden being built: it carries the
  // element list plus the growth frontier (which vine is alive, where
  // its tip is), and each step reads that state to decide what happens.
  function _step(g, rnd) {
    const el = g.elements;
    const res = { type: null, added: [], transformed: [] };

    function push(e) { el.push(e); res.added.push(el.length - 1); return el.length - 1; }
    function vineNode(band, u, v) {
      push({ k: 'vine', band: band, u: u, v: v });
      g.tip = { band: band, u: u, v: v };
    }
    // A transformation remembers WHAT IT WAS. The renderer needs that
    // to show a bud actually opening rather than a flower appearing
    // where a bud used to be — and only a genuine kind change gets a
    // ghost, so promoting a fruit to a pair does not sprout a phantom
    // flower.
    function change(ix, e) { (res.was || (res.was = {}))[ix] = el[ix].k; el[ix] = e; res.transformed.push(ix); }
    function touch(ix) { if (res.transformed.indexOf(ix) < 0) res.transformed.push(ix); }
    function jitter(x, amt) { return Math.max(0, Math.min(1, x + (rnd() - 0.5) * amt)); }
    // CONTROLLED VARIETY, not decoration. One seeded draw picks how a
    // leaf expresses itself — a single blade, a young curled one, or a
    // facing pair. The garden never gains an element for it: a pair is
    // ONE leaf drawn as two blades, so the density ceiling, the replay
    // and the element count are all untouched. "Do not make the Garden
    // grow more. Make the growth more interesting."
    function leafForm(curl, pair) {
      const r = rnd();
      if (r < curl) return 'curl';
      if (r < curl + pair) return 'pair';
      return 'plain';
    }
    function pickIx(fn) {
      const ixs = [];
      for (let i = 0; i < el.length; i++) if (fn(el[i])) ixs.push(i);
      return ixs.length ? ixs[Math.floor(rnd() * ixs.length)] : -1;
    }

    // Past the ceiling the garden DEEPENS instead of spreading — the
    // element count NEVER rises again. What it does instead is a pool
    // of STATE TRANSFORMATIONS, picked by the seeded rng: a bud opens,
    // a flower ripens, a leaf fills out, a flower opens wider, fruit
    // comes in pairs, a sprig forks. Scale is deliberately NOT in that
    // pool — it is the fallback for when nothing is left to transform,
    // because a garden whose only late behaviour is "the same leaves
    // get slightly bigger" has stopped answering the child.
    if (el.length >= DENSITY_CEILING) {
      const budIx = el.findIndex(function (e) { return e.k === 'bud'; });
      const flIx = el.findIndex(function (e) { return e.k === 'flower'; });
      const pool = [];
      if (budIx >= 0) pool.push('open_bud');
      if (flIx >= 0) pool.push('ripen_flower');
      if (el.some(function (e) { return e.k === 'leaf' && LEAF_FORMS.indexOf(e.f || 'plain') < LEAF_FORMS.length - 1; })) pool.push('fill_leaf');
      if (el.some(function (e) { return e.k === 'flower' && FLOWER_FORMS.indexOf(e.f || 'plain') < FLOWER_FORMS.length - 1; })) pool.push('open_flower');
      if (el.some(function (e) { return e.k === 'fruit' && (e.f || 'plain') === 'plain'; })) pool.push('pair_fruit');
      if (el.some(function (e) { return e.k === 'sprig' && (e.f || 'plain') === 'plain'; })) pool.push('fork_sprig');
      const act = pool.length ? pool[Math.floor(rnd() * pool.length)] : 'grow_leaf';
      if (act === 'open_bud') {
        const b = el[budIx];
        change(budIx, { k: 'flower', band: b.band, u: b.u, v: b.v, f: rnd() < 0.3 ? 'open' : 'plain' });
        res.type = 'bud_opened';
      } else if (act === 'ripen_flower') {
        const f = el[flIx];
        change(flIx, { k: 'fruit', band: f.band, u: f.u, v: f.v, f: rnd() < 0.25 ? 'pair' : 'plain' });
        res.type = 'flower_ripened';
      } else if (act === 'fill_leaf') {
        const ix = pickIx(function (e) { return e.k === 'leaf' && LEAF_FORMS.indexOf(e.f || 'plain') < LEAF_FORMS.length - 1; });
        el[ix].f = LEAF_FORMS[LEAF_FORMS.indexOf(el[ix].f || 'plain') + 1];
        touch(ix); res.type = 'leaf_grew';
      } else if (act === 'open_flower') {
        const ix = pickIx(function (e) { return e.k === 'flower' && FLOWER_FORMS.indexOf(e.f || 'plain') < FLOWER_FORMS.length - 1; });
        el[ix].f = FLOWER_FORMS[FLOWER_FORMS.indexOf(el[ix].f || 'plain') + 1];
        touch(ix); res.type = 'flower_bloomed';
      } else if (act === 'pair_fruit') {
        const ix = pickIx(function (e) { return e.k === 'fruit' && (e.f || 'plain') === 'plain'; });
        el[ix].f = 'pair'; touch(ix); res.type = 'flower_ripened';
      } else if (act === 'fork_sprig') {
        const ix = pickIx(function (e) { return e.k === 'sprig' && (e.f || 'plain') === 'plain'; });
        el[ix].f = 'fork'; touch(ix); res.type = 'branch_created';
      } else {
        // The last resort, and it is still a real change: a leaf that
        // has room grows into it; a garden with nothing left to promote
        // rearranges one blade rather than doing nothing at all. There
        // is no path out of this branch that reports no change.
        let ix = pickIx(function (e) { return e.k === 'leaf' && (e.s || 1) < 1.35; });
        if (ix >= 0) { el[ix].s = Math.min(1.35, (el[ix].s || 1) + 0.12); touch(ix); }
        else {
          ix = pickIx(function (e) { return e.k === 'leaf'; });
          if (ix >= 0) { el[ix].f = LEAF_FORMS[(LEAF_FORMS.indexOf(el[ix].f || 'plain') + 1) % LEAF_FORMS.length]; touch(ix); }
        }
        res.type = 'leaf_grew';
      }
      return res;
    }

    const stage = g.stepCount;

    // Zone 1 — the origin: the very first capture plants one sprig at
    // the foot of the left margin. The garden's fixed point, forever.
    if (stage === 0) {
      push({ k: 'sprig', band: 'left', u: 0.55, v: 0.94, s: 1.1 });
      g.tip = { band: 'left', u: 0.5, v: 0.9 };
      res.type = 'origin_created';
      return res;
    }

    // Zone 2 — nearby growth: a young vine curls upward from the origin,
    // SLOWLY, leafing as it goes — at a dozen captures the garden should
    // read as a leafy young cluster, never a floor-to-ceiling wire (the
    // product owner, at 13 captures: the vine had already spanned the
    // column with bare stretches between tiny leaves). Leaves are the
    // whole variation here: the first four captures are about ONE plant
    // establishing itself, so nothing forks and nothing branches yet.
    if (stage < 5) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      vineNode('left', jitter(0.5, 0.18), g.tip.v - 0.045 - rnd() * 0.02);
      push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: g.tip.v, s: 0.8 + rnd() * 0.25, f: leafForm(0.28, 0) });
      res.type = 'vine_extended';
      return res;
    }

    // Zone 3 — edge travel: the vine keeps climbing, still unhurried
    // (it reaches the upper half only around twenty captures), leaves
    // in pairs along the way, a sprig branching now and then — and a
    // sprig can now fork, which is the first hint of the branching
    // phase to come.
    if (stage < 13) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      let type = 'leaf_added';
      if (g.tip.band === 'left' && g.tip.v > 0.45) { vineNode('left', jitter(0.47, 0.18), g.tip.v - 0.055 - rnd() * 0.025); type = 'vine_extended'; }
      else if (rnd() < 0.4) { push({ k: 'sprig', band: 'left', u: jitter(0.5, 0.3), v: g.tip.v + 0.15 + rnd() * 0.3, s: 0.8 + rnd() * 0.2, f: rnd() < 0.3 ? 'fork' : 'plain' }); type = 'branch_created'; }
      push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: jitter(g.tip.v, 0.02), s: 0.8 + rnd() * 0.25, f: leafForm(0.2, 0.18) });
      res.type = type;
      return res;
    }

    // Zone 4 — branching: the left vine finishes its climb; the right
    // side begins from its own foot; sprigs reach the mid-margins.
    if (stage < 24) {
      const side = (stage % 2 ? 1 : -1) * 0.18;
      if (g.tip.band === 'left' && g.tip.v > 0.14) {
        vineNode('left', jitter(0.47, 0.18), g.tip.v - 0.06 - rnd() * 0.03);
        push({ k: 'leaf', band: 'left', u: jitter(g.tip.u + side, 0.06), v: jitter(g.tip.v, 0.02), s: 0.8 + rnd() * 0.25, f: leafForm(0.18, 0.22) });
        res.type = 'vine_extended';
        return res;
      }
      // A NEW CHAPTER, not another leaf (the sprint is explicit about
      // capture 18). The right side does not begin as a bare node — it
      // arrives with its own foot and its own first blade, so what the
      // child sees is a second plant starting rather than one more
      // increment of the first.
      if (!g.rightBorn && (stage === 18 || (g.tip.band !== 'right' && rnd() < 0.4))) {
        g.rightBorn = true;
        vineNode('right', jitter(0.5, 0.18), 0.95);
        push({ k: 'sprig', band: 'right', u: jitter(0.52, 0.12), v: 0.9, s: 0.9 + rnd() * 0.2, f: 'fork' });
        push({ k: 'leaf', band: 'right', u: jitter(0.55, 0.1), v: 0.92, s: 0.9 + rnd() * 0.2, f: leafForm(0, 0.4) });
        res.type = 'vine_born';
        return res;
      }
      if (g.tip.band === 'right' && g.tip.v > 0.5) {
        vineNode('right', jitter(0.5, 0.18), g.tip.v - 0.06 - rnd() * 0.03);
        push({ k: 'leaf', band: 'right', u: jitter(g.tip.u + side, 0.06), v: g.tip.v, s: 0.8 + rnd() * 0.25, f: leafForm(0.18, 0.22) });
        res.type = 'vine_extended';
        return res;
      }
      push({ k: 'sprig', band: rnd() < 0.5 ? 'left' : 'right', u: jitter(0.5, 0.25), v: 0.25 + rnd() * 0.5, s: 0.8 + rnd() * 0.2, f: rnd() < 0.45 ? 'fork' : 'plain' });
      res.type = 'branch_created';
      return res;
    }

    // Anything that grows from here on grows ON a vine — a leaf or bud
    // in mid-air is decoration, and decoration was the "nope". The
    // anchor is a real vine node, chosen by the seeded rng.
    function onVine(kind, extra) {
      const vines = el.filter(function (e) { return e.k === 'vine'; });
      if (!vines.length) return false;
      const a = vines[Math.floor(rnd() * vines.length)];
      const side = (Math.floor(rnd() * 2) ? 1 : -1) * 0.16;
      push(Object.assign({ k: kind, band: a.band, u: jitter(a.u + side, 0.05), v: jitter(a.v, 0.02) }, extra || {}));
      return true;
    }

    // Zone 5 — connections: the right edge finishes its climb and the
    // top arc closes, so both sides read as ONE garden. First buds.
    if (stage < 40) {
      if (g.tip.band === 'right' && g.tip.v > 0.12) {
        vineNode('right', jitter(0.5, 0.18), g.tip.v - 0.09 - rnd() * 0.04);
        if (rnd() < 0.6) push({ k: 'leaf', band: 'right', u: jitter(g.tip.u + 0.16, 0.05), v: g.tip.v, s: 0.8 + rnd() * 0.2, f: leafForm(0.2, 0.2) });
        res.type = 'vine_extended';
        return res;
      }
      if (!g.topClosed) {
        g.topClosed = true;
        for (let u = 0.4; u <= 0.96; u += 0.14) push({ k: 'vine', band: 'top', u: u, v: jitter(0.5, 0.3) });
        res.type = 'connection_created';
        return res;
      }
      if (rnd() < 0.35 && onVine('bud', { f: rnd() < 0.22 ? 'pair' : 'plain' })) { res.type = 'bud_created'; return res; }
      onVine('leaf', { s: 0.75 + rnd() * 0.25, f: leafForm(0.22, 0.2) });
      res.type = 'leaf_added';
      return res;
    }

    // Zone 6 — blossoming, then FRUIT: flowers open where the vine is
    // OLDEST — near the origin first — and from the mid-fifties an
    // open flower now and then ripens into a small amber fruit ("when
    // will we get buds, flowers, fruits" — the product owner; the
    // vine's seasons are: buds from ~24 captures, flowers from ~40,
    // fruit from ~55, and past the ceiling everything keeps ripening).
    // This is the most varied phase by design: every form in the
    // vocabulary is reachable here.
    if (stage >= 55 && rnd() < 0.18) {
      const fIx = el.findIndex(function (e) { return e.k === 'flower'; });
      if (fIx >= 0) {
        const f = el[fIx];
        change(fIx, { k: 'fruit', band: f.band, u: f.u, v: f.v, f: rnd() < 0.25 ? 'pair' : 'plain' });
        res.type = 'flower_ripened';
        return res;
      }
    }
    if (rnd() < 0.3) {
      const budIx = el.findIndex(function (e) { return e.k === 'bud'; });
      if (budIx >= 0) {
        const b = el[budIx];
        change(budIx, { k: 'flower', band: b.band, u: b.u, v: b.v, f: rnd() < 0.3 ? 'open' : 'plain' });
        res.type = 'bud_opened';
        return res;
      }
      push({ k: 'flower', band: 'left', u: jitter(0.5, 0.2), v: 0.86 - (g.flowers = (g.flowers || 0) + 1) * 0.12, f: rnd() < 0.25 ? 'open' : 'plain' });
      res.type = 'flower_bloomed';
      return res;
    }
    if (rnd() < 0.25 && onVine('bud', { f: rnd() < 0.22 ? 'pair' : 'plain' })) { res.type = 'bud_created'; return res; }
    onVine('leaf', { s: 0.75 + rnd() * 0.25, f: leafForm(0.22, 0.22) });
    res.type = 'leaf_added';
    return res;
  }

  function _build(seed, events) {
    const rnd = _rng(seed);
    const g = { elements: [], tip: null, stepCount: 0, topClosed: false, rightBorn: false };
    let last = null;
    for (let i = 0; i < events; i++) { last = _step(g, rnd); g.stepCount++; }
    return { elements: g.elements, last: last };
  }

  // ---- public surface ------------------------------------------------------
  // state() is what a RE-RENDER reads, and it deliberately carries no
  // growth report: rendering must never look like growing (the sprint's
  // replay/render safety rule). The growth report travels on the change
  // event, which only captured() ever fires.
  function state() {
    const rec = _load();
    return { events: rec.events, elements: _build(rec.seed, rec.events).elements };
  }

  // ONE CAPTURE = ONE GROWTH STEP, and the variety happens INSIDE the
  // step — never by taking two. What the renderer is handed is the
  // step's own report: which elements appeared, which ones changed
  // without appearing, and what the growth was called.
  function captured(detail) {
    const id = detail && detail.id ? String(detail.id) : null;
    const rec = _load();
    if (id) {
      if (rec.recentIds.indexOf(id) >= 0) return { ok: true, grew: false };   // one capture = one growth
      rec.recentIds.push(id);
      if (rec.recentIds.length > RECENT_IDS_MAX) rec.recentIds.splice(0, rec.recentIds.length - RECENT_IDS_MAX);
    }
    rec.events += 1;
    _save(rec);
    const built = _build(rec.seed, rec.events);
    const growth = built.last || { type: null, added: [], transformed: [] };
    _listeners.forEach(function (cb) { try { cb({ animate: true, growth: growth }); } catch (e) {} });
    return { ok: true, grew: true, growth: growth };
  }

  function onChange(cb) { if (typeof cb === 'function') _listeners.push(cb); }

  try {
    document.addEventListener('vihu:creation-captured', function (ev) {
      captured((ev && ev.detail) || {});
    });
  } catch (e) {}

  const api = { state: state, captured: captured, onChange: onChange, claim: claim };
  try { window.LivingGarden = api; } catch (e) {}
})();
